name: "Moo instead of Foo"
description: "Moo"  
outputs:
  test-output:
    description: Test value
    value: This is a test value
  final-output:
    description: The output of the steps
    value: ${{ steps.moobar.outputs.output }}
runs:
  using: composite
  steps:
    - name: Foobar
      id: foobar
      shell: bash
      run: |
        echo "foobar"
      continue-on-error: true
    - name: Moobar
      id: moobar
      shell: bash
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "output<<$EOF" >> $GITHUB_OUTPUT
        sed --help 2>&1 >> $GITHUB_OUTPUT
        echo "foobar" | sed -E s/foo/moo/g >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
        
      continue-on-error: true
